Repository yasasii-team/Stepippo-iOS, pull requests merged in 2019-05, with the labels that each got.

#79 進捗画面のstoryboardとUIViewControllerファイルを作成
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Controllers/ProgVC.swift
  Stepippo/Classes/Views/Prog.storyboard
Labels: enhancement

#93 RealmをCarthageでインストールしました
  Cartfile
  Cartfile.resolved
  README.md
  Stepippo.xcodeproj/project.pbxproj
Labels: enhancement

#90 ListedIPPO画面に必要なVCとNavigationControllerを追加しました
  Stepippo/Classes/Views/ListedIPPO.storyboard
Labels: enhancement

#95 TabBarControllerを追加して、3画面と繋ぎました
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Controllers/ViewController.swift
  Stepippo/Classes/Views/Base.lproj/Main.storyboard
Labels: enhancement

#97 その他画面のTabBarItemのアイコンを追加しました
  Stepippo/Classes/Views/Misc.storyboard
  Stepippo/Resources/Assets.xcassets/MiscImage/More.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/MiscImage/More.imageset/icons8-more-1.png
  Stepippo/Resources/Assets.xcassets/MiscImage/More.imageset/icons8-more-2.png
  Stepippo/Resources/Assets.xcassets/MiscImage/More.imageset/icons8-more.png
Labels: enhancement

#96 【進捗画面】Tab Bar Item を追加してアイコンとTitleを設定
  Stepippo/Classes/Views/Prog.storyboard
Labels: enhancement

#119 【進捗画面】storyboardにパーツを配置した
  Stepippo/Classes/Views/Prog.storyboard
  Stepippo/Resources/Assets.xcassets/ProgImage/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskCompleted.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskCompleted.imageset/icons8-task_completed-1.png
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskCompleted.imageset/icons8-task_completed-2.png
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskCompleted.imageset/icons8-task_completed.png
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon-塗りあり.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon-塗りあり.imageset/icons8-task-completed-filled-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon-塗りなし.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon-塗りなし.imageset/icons8-task-completed-filled-50 (1).png
  Stepippo/Resources/Assets.xcassets/ProgImage/boder角細.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/boder角細.imageset/icons8-水平線-filled-50 (1).png
  Stepippo/Resources/Assets.xcassets/ProgImage/border角太 黒.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/border角太 黒.imageset/icons8-水平線-24.png
  Stepippo/Resources/Assets.xcassets/ProgImage/border角太.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/border角太.imageset/icons8-水平線-filled-30.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-太枠.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-太枠.imageset/icons8-unchecked-checkbox-filled-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-細枠.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-細枠.imageset/icons8-unchecked-checkbox-filled-50 (1).png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-透明レ点.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-透明レ点.imageset/icons8-checked-checkbox-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-黒レ点.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-黒レ点.imageset/icons8-checked-checkbox-filled-50.png
Labels: enhancement

#120 タスク選択画面の各コンポーネント追加
  Stepippo/Classes/Views/GoalSetting.storyboard
Labels: enhancement

#130 TextFieldを削除し、Buttonに変更しました
  Stepippo/Classes/Views/Prog.storyboard
Labels: enhancement

#126 チェックボタン実装用のファイルを作成
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Controllers/ProgCheckButton.swift
Labels: enhancement

#131 タスク選択画面の詳細レイアウトを設定
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Util/UIView+Extension.swift
  Stepippo/Classes/Views/GoalSetting.storyboard
Labels: enhancement

#136 タスク選択画面での画面遷移の実装
  Stepippo/Classes/Controllers/GoalSettingVC.swift
  Stepippo/Classes/Views/GoalSetting.storyboard
Labels: discussion(議論), enhancement

#127 進捗画面のStackView作成と制約の設定
  Stepippo/Classes/Views/Prog.storyboard
Labels: enhancement

#142 [進捗画面]TabBarIconの拡大表示を修正
  Stepippo/Classes/Views/Prog.storyboard
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon-塗りあり.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon-塗りなし.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon-塗りなし.imageset/icons8-task-completed-filled-50 (1).png
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon.imageset/icons8-task-completed-filled-25.png
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon.imageset/icons8-task-completed-filled-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/TaskIcon.imageset/icons8-task-completed-filled-75.png
  Stepippo/Resources/Assets.xcassets/ProgImage/boder角細.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/boder角細.imageset/icons8-水平線-filled-50 (1).png
  Stepippo/Resources/Assets.xcassets/ProgImage/border角太 黒.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/border角太 黒.imageset/icons8-水平線-24.png
  Stepippo/Resources/Assets.xcassets/ProgImage/border角太.imageset/icons8-水平線-filled-30.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-1.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-1.imageset/icons8-unchecked-checkbox-25.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-1.imageset/icons8-unchecked-checkbox-75.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-1.imageset/icons8-unchecked-checkbox-filled-50 (1).png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-太枠.imageset/icons8-unchecked-checkbox-filled-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-細枠.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-透明レ点.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox-黒レ点.imageset/icons8-checked-checkbox-filled-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox.imageset/icons8-checked-checkbox-25.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox.imageset/icons8-checked-checkbox-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/checkbox.imageset/icons8-checked-checkbox-75.png
Labels: enhancement

#144 タスク登録画面のTextField周りの実装
  Stepippo/Classes/Controllers/GoalSettingVC.swift
  Stepippo/Classes/Views/GoalSetting.storyboard
Labels: enhancement

#146 StackViewのAutoLayout設定
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Views/Prog.storyboard
Labels: enhancement

#152 【進捗画面】チェックボタンの実装
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Controllers/ProgCheckButton.swift
  Stepippo/Classes/Controllers/ProgVC.swift
  Stepippo/Classes/Views/CheckButton.swift
  Stepippo/Classes/Views/Prog.storyboard
  Stepippo/Resources/Assets.xcassets/ProgImage/Checkbox.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/Checkbox.imageset/icons8-checked-checkbox-25.png
  Stepippo/Resources/Assets.xcassets/ProgImage/Checkbox.imageset/icons8-checked-checkbox-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/Checkbox.imageset/icons8-checked-checkbox-75.png
  Stepippo/Resources/Assets.xcassets/ProgImage/UnCheckbox.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/UnCheckbox.imageset/icons8-unchecked-checkbox-25.png
  Stepippo/Resources/Assets.xcassets/ProgImage/UnCheckbox.imageset/icons8-unchecked-checkbox-75.png
  Stepippo/Resources/Assets.xcassets/ProgImage/UnCheckbox.imageset/icons8-unchecked-checkbox-filled-50 (1).png
Labels: enhancement

#157 ActionSheetの実装
  Stepippo/Classes/Controllers/ProgVC.swift
  Stepippo/Classes/Views/Prog.storyboard
Labels: enhancement

#154 ストックIPPO表示画面を実装
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Controllers/StockedIPPOVC.swift
  Stepippo/Classes/Util/Date+Extension.swift
  Stepippo/Classes/Views/StockedIPPO.storyboard
Labels: enhancement

#161 チェックボタンのアニメーションを実装
  Stepippo/Classes/Controllers/ProgVC.swift
  Stepippo/Classes/Views/CheckButton.swift
  Stepippo/Classes/Views/Prog.storyboard
  Stepippo/Resources/Assets.xcassets/ProgImage/Check_off.imageset/Check-off-25.png
  Stepippo/Resources/Assets.xcassets/ProgImage/Check_off.imageset/Check-off-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/Check_off.imageset/Check-off-75.png
  Stepippo/Resources/Assets.xcassets/ProgImage/Check_off.imageset/Contents.json
  Stepippo/Resources/Assets.xcassets/ProgImage/Check_on.imageset/Check-ok-25.png
  Stepippo/Resources/Assets.xcassets/ProgImage/Check_on.imageset/Check-ok-50.png
  Stepippo/Resources/Assets.xcassets/ProgImage/Check_on.imageset/Check-ok-75.png
  Stepippo/Resources/Assets.xcassets/ProgImage/Check_on.imageset/Contents.json
Labels: enhancement

#168 プロジェクト設定
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Resources/Info.plist
Labels: good first issue(やさしい)
