Repository yasasii-team/Stepippo-iOS, pull requests merged in 2019-06, with the labels that each got.

#170 変更した期間をUserDefaultsで保存
  Stepippo/Classes/Controllers/ProgVC.swift
  Stepippo/Classes/Views/Prog.storyboard
Labels: enhancement

#175 画面表示時、UserDefaultsに保存してある「期間」を読み込む実装
  Stepippo/Classes/Controllers/ProgVC.swift
Labels: enhancement

#189 曜日を記憶するUserDefaultsの型をIntに変更
  Stepippo/Classes/Controllers/MiscVC.swift
Labels: refactoring(改修)

#171 タスク選択画面のTableView実装
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Controllers/GoalSettingVC.swift
  Stepippo/Classes/Views/AddTaskCell.swift
  Stepippo/Classes/Views/AddTaskCell.xib
  Stepippo/Classes/Views/GoalSetting.storyboard
Labels: enhancement

#190 #189 の変更に対応
  Stepippo/Classes/Controllers/AchievedIPPOVC.swift
  Stepippo/Classes/Views/AchievedIPPO.storyboard
Labels: refactoring(改修)

#193 設定してある1日の開始時刻を表示できるようにしました
  Stepippo/Classes/Controllers/MiscVC.swift
Labels: enhancement

#201 残り期間をLabelに表示する
  Stepippo/Classes/Controllers/ProgVC.swift
  Stepippo/Classes/Views/Prog.storyboard
Labels: enhancement

#205 達成数をLabeに表示する
  Stepippo/Classes/Controllers/ProgVC.swift
  Stepippo/Classes/Views/Prog.storyboard
Labels: enhancement

#206 StockedIPPOVCの課題を修正
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Controllers/StockedIPPOVC.swift
  Stepippo/Classes/Util/UIScrollView+Extension.swift
  Stepippo/Classes/Views/StockedIPPO.storyboard
Labels: bug

#207 RealmObjectAccessibleをIPPO専用にして、プライマリキーをStringに変更
  Stepippo.xcodeproj/project.pbxproj
  Stepippo/Classes/Controllers/AchievedIPPOVC.swift
  Stepippo/Classes/Controllers/GoalSettingVC.swift
  Stepippo/Classes/Controllers/ProgVC.swift
  Stepippo/Classes/Controllers/StockedIPPOVC.swift
  Stepippo/Classes/Models/IPPORepository.swift
Labels: bug, refactoring(改修)
